# Generated by Django 5.1.7 on 2025-03-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_board_node_board"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="created_at",
        ),
        migrations.AddField(
            model_name="node",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="nodes.board",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="wikidata_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
