# Generated by Django 5.1.7 on 2025-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_manualedge_created_by_node_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="editrequest",
            name="read_by_sender",
            field=models.BooleanField(default=False),
        ),
    ]
