# Generated by Django 5.1.7 on 2025-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0006_contributionmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
