# Generated by Django 5.1.7 on 2025-03-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0003_remove_node_created_at_node_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="wikidata_id",
        ),
    ]
