# Generated by Django 5.1.7 on 2025-04-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_remove_node_wikidata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.board')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_edges_from', to='nodes.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_edges_to', to='nodes.node')),
            ],
        ),
    ]
